const GRID_TYPES = {
  CREATE_GRID: "CREATE_GRID",
  CREATE_MAZE: "CREATE_MAZE",
  FIND_PATH: "FIND_PATH",
  MARK_CELL_VISITED: "MARK_CELL_VISITED",
  MARK_SHORTEST_PATH: "MARK_SHORTEST_PATH",
  RESET_VISITED_AND_SP: "RESET_VISITED_AND_SP",
  ADD_WEIGHTS: "ADD_WEIGHTS",
  W_KEY_PRESS: "W_KEY_PRESS",
  CELL_CLICKED: "CELL_CLICKED",
  DRAG_DROP: "DRAG_DROP",
  MOUSE_DOWN: "MOUSE_DOWN",
  MOUSE_OVER: "MOUSE_OVER",
};

export default GRID_TYPES;
